stages:
  - build
  - deploy
variables:
  DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  DOCKER_TLS_CERTDIR: ""
  KUBECONFIG: "/home/gitlab-runner/.kube/config"

.build:
  services:
    - name: docker:dind
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t ""$DOCKER_IMAGE_NAME"" ./docker
    - docker push "$DOCKER_IMAGE_NAME"

deploy:
  stage: deploy
  extends: .build
  script:
    - envsubst < diploma_app.yaml | kubectl apply -f -
  rules:
    - if: $CI_COMMIT_TAG